# Generated by Django 5.2 on 2025-04-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_note_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"verbose_name": "Notes", "verbose_name_plural": "Notes List"},
        ),
        migrations.AlterModelTable(
            name="note",
            table="notes",
        ),
    ]
