# Generated by Django 5.2 on 2025-04-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_note_options_alter_note_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
