# Generated by Django 5.2 on 2025-04-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_note_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
