# Generated by Django 5.2 on 2025-04-23 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_note_deleted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="note",
            constraint=models.UniqueConstraint(
                fields=("user", "title"), name="unique_note_title_per_user"
            ),
        ),
    ]
